### ISSUE TITLE
Support Python 3 for TensorFlow scripts

### ISSUE THREAD

**Issue by meownoid** [aws/sagemaker-python-sdk#19]
Is there any reason not to do this? Python 2 is an officially outdated language and will retire in 2 years.

**Comment by iquintero** [comment]
Hi @meownoid 

Thanks for your interest in Sagemaker!  Support for python3 is definitively important! it just didn't make the cut for launch. This is on our backlog, and we'll give you an update when we have an ETA.

**Comment by aidan-plenert-macdonald** [comment]
+1 Python2.7 is old and the inconsistency is annoying,

```
Traceback (most recent call last):
  File "/opt/amazon/bin/entry.py", line 32, in <module>
    modes[mode]()
  File "/opt/amazon/lib/python2.7/site-packages/container_support/training.py", line 21, in start
    raise e
  File "/opt/ml/code/lstm-trainer.py", line 55
    logging.info(f'[Epoch {epoch}] Training: {name}={acc}')
                                                         ^
SyntaxError: invalid syntax
```

**Comment by flexthink** [comment]
+1: Given the lack of backwards compatibility, I wouldn't want to start using a tool that locks me into Python 2.x for new projects

**Comment by adogyf** [comment]
Hi @iquintero
Can we get an estimate for python3 compatibility?

**Comment by aidan-plenert-macdonald** [comment]
@andremoeller Is there an open Dockerfile for the default container? If so, I'd happily submit a PR.

**Comment by andremoeller** [comment]
Hi @aidan-plenert-macdonald ,

We're actively working on open-sourcing our Dockerfiles, but we don't have one open-sourced yet. Thanks!

**Comment by mlaicode** [comment]
Hi @iquintero Any further update since early March for python3 compatibility ?

**Comment by pranavmodi** [comment]
Hello, my organization is considering using Sagemaker. It fits our usecase very well - but support for Python 3 is needed. Is there any timeline for supporting it? Thanks!

**Comment by cniedzwiedz** [comment]
+1 for Python3 support

**Comment by YashalShakti** [comment]
+1 for Python3 support

**Comment by YashalShakti** [comment]
+1 for Python 3 support

**Comment by hl037** [comment]
+1

**Comment by kalpitsmehta** [comment]
+1 for Python 3 support

**Comment by rparundekar** [comment]
+1

**Comment by yyolk** [comment]
+1

**Comment by Jsturgeo** [comment]
+1

**Comment by ShukuiZhang** [comment]
+1

**Comment by gdj0nes** [comment]
+1

**Comment by sharmasx** [comment]
+1

**Comment by adkatrit** [comment]
+1

**Comment by laurenyu** [comment]
Hi all, thanks for letting us know how important this feature is to you! We've released Python 3 support for TF in #475 - though it does require a new training script format. Documentation is on its way, but I wanted to post an update here letting you know that you can now use our Python 3 TF images

**Comment by frankgu** [comment]
I am still getting an ERROR "ClientError: Cannot pull algorithm container" 
when I was trying to run the following code

```
...
estimator = TensorFlow(
    entry_point='endpoint.py',
    source_dir=source_dir,
    role=role,
    output_path=model_artifacts_location,
    code_location=custom_code_upload_location,
    train_instance_count=1,
    train_volume_size=30,  # GB
    framework_version='1.8.0',
    train_instance_type=train_instance_type,
    py_version='py3',
    hyperparameters=HYPERPARAMETERS)

estimator.fit(data_location, run_tensorboard_locally=False)
```

**Comment by mvsusp** [comment]
Closing this issue now that we have official support for [python 3](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/tensorflow/README.rst#training-with-tensorflow).

🎉 🎈
