### ISSUE TITLE
transformer() method for an SKLearn estimator is failing

### ISSUE THREAD

**Issue by lihip** [aws/sagemaker-python-sdk#974]
Please fill out the form below.

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: SKLearn
- **Framework Version**: sagemaker 1.36.1
- **Python Version**: 3.6
- **CPU or GPU**: CPU
- **Python SDK Version**: sagemaker 1.36.1
- **Are you using a custom image**: yes, using entry point script

### Describe the problem
An SKLearn estimator that is based on a custom algorithm (using entry_point script) was fitted and created a training job. Then, when calling the transformer method of that estimator with instance_count and instance_type parameters, a TypeError is thrown.

### Minimal repro / logs
- **Exact command to reproduce**:
sklearn = SKLearn(
    entry_point=script_path,
    train_instance_type="ml.m5.large",
    role=role,
    output_path =output_location,
    code_location=code_location,
    hyperparameters={'min_child_weight': 2, 'max_depth':8})
transformer = sklearn.transformer(instance_count=1, instance_type='ml.m5.large')
Error:
TypeError: __init__() got multiple values for argument 'entry_point'

- **Stack trace:**
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-20-07fcf819e9f1> in <module>()
----> 1 transformer = sklearn.transformer(instance_count=1, instance_type='ml.m5.large')

~/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker/estimator.py in transformer(self, instance_count, instance_type, strategy, assemble_with, output_path, output_kms_key, accept, env, max_concurrent_transforms, max_payload, tags, role, model_server_workers, volume_kms_key, entry_point)
   1573         if self.latest_training_job is not None:
   1574             model = self.create_model(
-> 1575                 role=role, model_server_workers=model_server_workers, entry_point=entry_point
   1576             )
   1577 

~/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker/sklearn/estimator.py in create_model(self, model_server_workers, role, vpc_config_override, **kwargs)
    167             sagemaker_session=self.sagemaker_session,
    168             vpc_config=self.get_vpc_config(vpc_config_override),
--> 169             **kwargs
    170         )
    171 

TypeError: __init__() got multiple values for argument 'entry_point'

**Comment by jesterhazy** [comment]
Hi @lihip, thanks for using SageMaker!

I haven't been able to reproduce this issue. Can you provide the rest of the code you used that led to this error (e.g. the training part too).

**Comment by dolarte** [comment]
Same error for me.
sagemaker 1.36.0 was installed, but the error went away when I pip installed sagemaker==1.33.0.

**Comment by lihip** [comment]
```
role = get_execution_role()
script_path = 'xgboost_model2.py'
sklearn = SKLearn(
    entry_point=script_path,
    train_instance_type="ml.m5.large",
    role=role,
    output_path = output_location,
    code_location=code_location,
    hyperparameters={'min_child_weight': 2, 'max_depth':8})
sklearn.fit({'train': train_input, 'validation': validation_input})
transformer = sklearn.transformer(instance_count=1, instance_type='ml.m5.large')
```
[xgboost_model2.zip](https://github.com/aws/sagemaker-python-sdk/files/3494077/xgboost_model2.zip)

**Comment by jesterhazy** [comment]
@lihip and @dolarte 

I was able to reproduce this in 1.36.0, but the problem is fixed in the current version 1.36.2. Just upgrade your copy of the sagemaker python sdk to the latest version.

**Comment by scrooks** [comment]
Updated to 1.36.2 locally and it still fails exactly the same way for me.  Works under `1.33.0`.  It now fails on AWS notebooks in the `conda_python3` kernel, which worked last week and which I confirmed last week had `1.33.0` running, which is how I figured out I needed to not run `1.36.0` locally.  Now today `conda_python3` has `1.36.0` which is failing with this error.

**Comment by jesterhazy** [comment]
Thanks @scrooks, you're right.

It looks like this is a regression introduced in 1.34.1. We should have a fix out shortly, but in the meantime you can work around this by using 1.34.0 instead.

If you are in a SageMaker notebook, you can install this version by running a cell with 

`!pip install -U sagemaker==1.34.0`

and then restarting your notebook kernel.

**Comment by jesterhazy** [comment]
sagemaker 1.36.3 was released this morning with the fix for this issue.

**Comment by lihip** [comment]
Thank you!
